CREATE TABLE supplier (
SNO TEXT PRIMARY KEY,
SNAME TEXT,
STATUS INTEGER,
CITY TEXT
);
INSERT INTO supplier(SNO,SNAME,STATUS,CITY) VALUES
('S1','SAITH',20,'LONDON'),
('S1','Smith',10,'paris'),
('S1','jones',31,'paris'),
SELECT*FROM supplier 
